apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: autograder

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
  - hpa.yaml
  - image-stream.yaml
  - build-config.yaml
  - externalsecret.yaml

secretGenerator:
  - name: autograder-config
    envs:
      - autograder.env
    options:
      disableNameSuffixHash: true
