#!/usr/bin/env bash

LINK="https://autograder-service-ope-test.apps.shift.nerc.mghpcc.org"
USERNAME="istaplet"
PASSWORD="123"
ASSIGNMENT_NAME="challenge-threads"

cd /autograder/submission
zip -r submission.zip . -x run_autograder README.md autograder.zip setup.sh run_autograder zip.sh

curl --user "$USERNAME:$PASSWORD" -X POST -F "submission.zip=@submission.zip" --form "assignment_name=$ASSIGNMENT_NAME" $LINK > /autograder/results/results.json
